### ISSUE TITLE
Kakogo huya?

### ISSUE THREAD

**Issue by ENSLERMAN** [BesedinAlex/guides-fusion360#4]
Why so many lines of code?
![Снимок](https://user-images.githubusercontent.com/32003802/69016136-66168c00-09ac-11ea-92b2-9d215e401cdf.PNG)

**Comment by BesedinAlex** [comment]
It probably counts some lines from binary files. I don’t see another reason. There were never so many lines of code ever. Another contributor also has insane amount of “code” but he didn’t commit any. He committed images only.

**Comment by BesedinAlex** [comment]
I contacted Github Help for help.
